- name: Gather and local-save remote host facts
  hosts: all
  gather_facts: true  
  vars:
    repo_dir: "./devicedata"
  tasks:
    - name: Pull latest changes
      ansible.builtin.git:
        repo: "https://github.com/bfarr-rh/devicedata.git"
        version: main
        update: true
    - name: Save gathered facts to JSON files on the control node
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "{{ repo_dir }}/{{ inventory_hostname }}_facts.json"
        mode: '0644'
      delegate_to: localhost
    - name: Git add
      ansible.builtin.command:
        cmd: git add .
        chdir: "{{ repo_dir }}"
    - name: Git commit
      ansible.builtin.command:
        cmd: git commit -m "Update files from Ansible"
        chdir: "{{ repo_dir }}"
      register: git_commit
      failed_when:
      - git_commit.rc != 0
      - "'nothing to commit' not in git_commit.stdout"
    - name: Git push
      ansible.builtin.command:
        cmd: git push origin main
        chdir: "{{ repo_dir }}"
      when: git_commit.rc == 0
