---
- name: Listen for Configuration Alerts from Kafka
  hosts: all
  sources:
    - ansible.eda.url_check:
        # Calls the Kafka Bridge consumer endpoint
        urls:
          - "http://kafka-bridge-kafka.apps.sno.int.apac-tech-lab.net/topics/config-alerts"
        interval: 5  # Polls every 5 seconds
        method: GET
        headers:
          Accept: "application/vnd.kafka.json.v2+json"
  rules:
    - name: Debug print all raw events
      condition: true  # <-- Automatically matches everything that hits the source
      action:
        debug:
          msg: "{{ event }}"  # <-- Natively exposes the entire structured payload
