---
- name: Listen for Configuration Alerts from Kafka
  hosts: all
  sources:
    - name: Config Alert Changes via Kafka topic
      ansible.eda.kafka:
        host: kafka-kafka-bootstrap.kafka.svc.cluster.local
        port: 9092
        topic: config-alerts
        group_id: eda-consumer-group
  rules:
    - name: Critical Event
      condition: event.body.event is search("CRITICAL")
      action:
        print_event:
          pretty: true
    - name: Trigger Job Template to investigate the device
      condition: event.body.event is search("CRITICAL")
      actions:
        - run_job_template:
            name: "Compliance Investigation on Device"
            organization: "fttx-demo"
            job_args:
              extra_vars:
                _host: "{{ event.body.host }}"
                _group: "{{ event.body.group }}"
