---
all:
  children:
    srlinux:
      vars:
        ansible_connection: ansible.netcommon.netconf
        ansible_port: 22
        ansible_user: admin
        ansible_password: "NokiaSrl1!"
      hosts:
        leaf-01:
          ansible_host: 172.25.113.30
        leaf-02:
          ansible_host: 172.25.113.31
    local:
      hosts:
        localhost:
          ansible_connection: local
