---
all:
  children:
    srlinux:
      vars:
        ansible_connection: ansible.netcommon.netconf
        ansible_user: admin
        ansible_password: "NokiaSrl1!"
        ansible_network_os: nokia.srlinux.srlinux
      hosts:
        leaf-01:
          ansible_host: 172.25.73.24
          ansible_port: 30471
        leaf-02:
          ansible_host: 172.25.73.24
          ansible_port: 31149
    local:
      hosts:
        localhost:
          ansible_connection: local
