---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ playbook_dir }}/.venv/bin/python"

  children:
    srlinux:
      vars:
        ansible_connection: ansible.netcommon.netconf
        ansible_port: 22
        ansible_user: admin
        ansible_password: "NokiaSrl1!"
        ansible_network_os: nokia.srlinux.srlinux
      hosts:
        leaf-01:
          ansible_host: 172.25.113.30
        leaf-02:
          ansible_host: 172.25.113.31
