- name: Gather and local-save remote host facts
  hosts: localhost
  gather_facts: false
  vars:
    repo_dir: "/runner/project/devicedata"
    repo_compliance_dir: "/runner/project/device_compliance"
    repo_compliance_golden_rules_dir: "/runner/project/device_compliance/golden_config/groups"
    version_prefix: "v1.0.0"
    baseline_branch: "baseline"
    target_kafka_topic: "config-alerts"
    _group: ""
    _host: ""
  tasks:
    - name: Pull latest changes
      ansible.builtin.git:
        repo: "https://github.com/bfarr-rh/devicedata.git"
        version: main
        dest: "{{ repo_dir }}"
      environment:
        GIT_SSL_NO_VERIFY: "true"
      delegate_to: localhost
      connection: local
      run_once: true
    - name: Pull Compliance rules
      ansible.builtin.git:
        repo: "https://github.com/bfarr-rh/device_compliance.git"
        version: master
        dest: "{{ repo_compliance_dir }}"
      environment:
        GIT_SSL_NO_VERIFY: "true"
      delegate_to: localhost
      connection: local
      run_once: true
    - name: Locate the most recent tag when the file was Compliant
      ansible.builtin.shell: |
        set -o pipefail
        git fetch --tags --force
        
        # Find the latest commit where the "COMPLIANT" string count changed
        # %H = Commit Hash, %ci = Commit Date
        commit_info=$(git log -G "COMPLIANT" --pretty=format:"%H|%ci" -n 1 -- "{{ _group }}/{{ _host }}/{{ _host }}-config.json")
        
        if [ -z "$commit_info" ]; then
            echo "The string 'COMPLIANT' was never found in the file's history."
            exit 0
        fi
        
        # Split the hash and date
        commit_hash=$(echo "$commit_info" | cut -d'|' -f1)
        commit_date=$(echo "$commit_info" | cut -d'|' -f2)
        
        # Find the closest tag associated with or following that commit
        closest_tag=$(git describe --tags --abbrev=0 "$commit_hash" 2>/dev/null || echo "No Tag Found")
        
        echo "Last Compliance Change Commit: $commit_hash"
        echo "Associated Tag: $closest_tag"
        echo "Change Date: $commit_date"

        # Compare changes with the compliance rules since that time
        # Pulls a list of files modified since the target timestamp
        cd {{repo_compliance_golden_rules_dir}}
        compliance_changes=$(git log --since="$commit_date" --pretty=format:"%cd | %an | %s" 2>/dev/null || echo "No Compliance Changes Found")
        echo "Compliance changes since last compliant on $commit_date : $compliance_changes"
      environment:
        GIT_SSL_NO_VERIFY: "true"
      args:
        chdir: "{{ repo_dir }}"
        executable: /bin/bash
      register: compliance_check
      changed_when: false
      delegate_to: localhost
      connection: local
      run_once: true
    - name: Display last compliant information
      ansible.builtin.debug:
        var: compliance_check.stdout_lines
      delegate_to: localhost
      connection: local
      run_once: true
