- name: Gather and local-save remote host facts
  hosts: localhost
  gather_facts: false
  vars:
    repo_dir: "/runner/project/devicedata"
    repo_compliance_dir: "/runner/project/device_compliance"
    repo_compliance_golden_rules_dir: "/runner/project/device_compliance/golden_config/groups"
    version_prefix: "v1.0.0"
    baseline_branch: "baseline"
    target_kafka_topic: "config-alerts"
    _group: ""
    _host: ""
  tasks:
    - name: Pull latest changes
      ansible.builtin.git:
        repo: "https://github.com/bfarr-rh/devicedata.git"
        version: main
        dest: "{{ repo_dir }}"
      environment:
        GIT_SSL_NO_VERIFY: "true"
      delegate_to: localhost
      connection: local
      run_once: true
    - name: Pull Compliance rules
      ansible.builtin.git:
        repo: "https://github.com/bfarr-rh/device_compliance.git"
        version: master
        dest: "{{ repo_compliance_dir }}"
      environment:
        GIT_SSL_NO_VERIFY: "true"
      delegate_to: localhost
      connection: local
      run_once: true
    - name: Locate the most recent tag when the file was compliant
      ansible.builtin.shell: |
        git fetch --tags --force
        
        # Get all tags sorted chronologically (oldest to newest)
        tags=($(git tag --sort=creatordate))

          
        # Loop backwards from the newest tag to the oldest
        for ((i=$(#tags[@])-1; i>=0; i--)); do
            tag="$(tags[i])"
            
            # Stream the file at this tag. If it does NOT contain the string, it is compliant.
            fname="{{ _group }}/{{ _host }}/{{ _host }}-config.json"
            echo $fname

        done
        
        echo "The file was never compliant in any historical tag."
        exit 1
      args:
        chdir: "{{ repo_dir }}"
        executable: /bin/bash
      register: compliance_check
      failed_when: false
      changed_when: false
      delegate_to: localhost
      connection: local
      run_once: true
    - name: Display last compliant information
      ansible.builtin.debug:
        var: compliance_check.stdout_lines
      delegate_to: localhost
      connection: local
      run_once: true
